export const APP_NAME = "CashCompass";
export const LOCAL_SUPABASE_PLACEHOLDER_URL = "http://127.0.0.1:54321";
export const LOCAL_SUPABASE_PLACEHOLDER_KEY = "local-development-anon-key";

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || LOCAL_SUPABASE_PLACEHOLDER_URL;
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || LOCAL_SUPABASE_PLACEHOLDER_KEY;

export const isSupabaseConfigured =
  SUPABASE_URL !== LOCAL_SUPABASE_PLACEHOLDER_URL ||
  SUPABASE_PUBLISHABLE_KEY !== LOCAL_SUPABASE_PLACEHOLDER_KEY;
